version: "3"

services:
    app:
        build: ./
        ports:
            - "8080:8080"
        working_dir: /app
        networks:
            - anser_project_network
        depends_on:
            - redis
            - rabbitmq
            - eventstoredb
        environment: 
            PHP_MEMORY_LIMIT: "2048M"
            PHP_MAX_EXECUTION_TIME: "600"
            PHP_POST_MAX_SIZE: "200M"
            PHP_UPLOAD_MAX_FILESIZE: "200M"
            XDEBUG_MODE: coverage

            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: root
            RABBITMQ_PASS: root

            EVENTSTOREDB_HOST: eventstoredb
            EVENTSTOREDB_PORT: 2113
        volumes:
            - './:/app'

    rabbitmq:
        container_name: rabbitmq
        image: 'rabbitmq:management'
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - anser_project_network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - anser_project_network

    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "8001:5540"
        networks:
            - anser_project_network

    eventstoredb:
        container_name: eventstoredb
        image: eventstore/eventstore:latest
        environment:
            EVENTSTORE_CLUSTER_SIZE: 1
            EVENTSTORE_RUN_PROJECTIONS: All
            EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
            EVENTSTORE_INSECURE: "true"
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
        ports:
            - "1113:1113"
            - "2113:2113"
        networks:
            - anser_project_network

networks:
  anser_project_network:
    driver: bridge
    external: true
